function mni2fs_addtoolbar

thisfolder = fileparts(mfilename('fullpath'));

if isempty(findobj(gcf,'type','uitoolbar'))
    tb = uitoolbar(gcf);
    iconright = double(imread([thisfolder '/../misc/icoright.png']))./255;
    iconright_yolk = double(imread([thisfolder '/../misc/icoright_yolk.png']))./255;
    iconyolk = double(imread([thisfolder '/../misc/yolk.png']))./255;

    for ii = 1:3
        iconrightrot(:,:,ii) = rot90(iconright(:,:,ii));
        iconrightrot_yolk(:,:,ii) = rot90(iconright_yolk(:,:,ii));
    end
    
    p = uipushtool(tb,'TooltipString','Rotate Nearside Right',...
        'ClickedCallback',...
        'V = get(gca,''View'');  V = V-[45 0];  view(V);','CData',iconright);
    p = uipushtool(tb,'TooltipString','Rotate Nearside Left',...
        'ClickedCallback',...
        'V = get(gca,''View'');  V = V+[45 0];  view(V);','CData',flipdim(iconright,2));
    p = uipushtool(tb,'TooltipString','Rotate Nearside Up',...
        'ClickedCallback',...
        'V = get(gca,''View'');  V = V-[0 45];  view(V);','CData',iconrightrot);
    p = uipushtool(tb,'TooltipString','Rotate Nearside Down',...
        'ClickedCallback',...
        'V = get(gca,''View'');  V = V+[0 45];  view(V);','CData',flipdim(iconrightrot,1));
    

    p = uipushtool(tb,'TooltipString','Rotate Nearside Right (Yoke)',...
        'ClickedCallback',...
        'V = get(gca,''view''); O = findobj(0,''Tag'',''overlay''); V = V-[45 0]; set(O,''View'',V)','CData',iconright_yolk);
    p = uipushtool(tb,'TooltipString','Rotate Nearside Left (Yoke)',...
        'ClickedCallback',...
        'V = get(gca,''view''); O = findobj(0,''Tag'',''overlay''); V = V+[45 0]; set(O,''View'',V)','CData',flipdim(iconright_yolk,2));
    p = uipushtool(tb,'TooltipString','Rotate Nearside Up (Yoke)',...
        'ClickedCallback',...
        'V = get(gca,''view''); O = findobj(0,''Tag'',''overlay''); V = V-[0 45]; set(O,''View'',V)','CData',iconrightrot_yolk);
    p = uipushtool(tb,'TooltipString','Rotate Nearside Down (Yoke)',...
        'ClickedCallback',...
        'V = get(gca,''view''); O = findobj(0,''Tag'',''overlay''); V = V+[0 45]; set(O,''View'',V)','CData',flipdim(iconrightrot_yolk,1));
    
    p = uipushtool(tb,'TooltipString','Yoke Others',...
        'ClickedCallback',...
        'V = get(gca,''view''); O = findobj(0,''Tag'',''overlay''); set(O,''View'',V)','CData',flipdim(iconyolk,1));
end